username: [placeholder]
password: [placeholder]
# k"m~z5+6~X-F.R8
phone_number: [placeholder]

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'

positions:
- Data
- Analytics

# Add more positions you want to search for

locations:
- Remote

# Add more locations you want to search in

salary: 100000-250000
rate: 50

# --------- Optional Parameters -------
uploads:
  Resume: [placeholder]
  Cover Letter: [placeholder]
  #Photo: # PATH TO photo (optional)

output_filename:
[placeholder]
# blacklist:
# - Company names you want to ignore
# - Example: - Google
# - Example: - Facebook

experience_level:
  # - 1 # Entry level
  - 2 # Associate
  - 3 # Mid-Senior level
  - 4 # Director
  # - 5 # Executive
  # - 6 # Internship
